//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOA_Client.SoapAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="SoapAPI.MyServicePortType")]
    public interface MyServicePortType {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (CreatePerson_Request) сообщения CreatePersonRequest не соответствует значению по умолчанию (CreatePerson).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_Client.SoapAPI.CreatePersonResponse CreatePerson(SOA_Client.SoapAPI.CreatePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.CreatePersonResponse> CreatePersonAsync(SOA_Client.SoapAPI.CreatePersonRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ListPeople_Request) сообщения ListPeopleRequest не соответствует значению по умолчанию (ListPeople).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_Client.SoapAPI.ListPeopleResponse ListPeople(SOA_Client.SoapAPI.ListPeopleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.ListPeopleResponse> ListPeopleAsync(SOA_Client.SoapAPI.ListPeopleRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ReadPerson_Request) сообщения ReadPersonRequest не соответствует значению по умолчанию (ReadPerson).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_Client.SoapAPI.ReadPersonResponse ReadPerson(SOA_Client.SoapAPI.ReadPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.ReadPersonResponse> ReadPersonAsync(SOA_Client.SoapAPI.ReadPersonRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (UpdatePerson_Request) сообщения UpdatePersonRequest не соответствует значению по умолчанию (UpdatePerson).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_Client.SoapAPI.UpdatePersonResponse UpdatePerson(SOA_Client.SoapAPI.UpdatePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.UpdatePersonResponse> UpdatePersonAsync(SOA_Client.SoapAPI.UpdatePersonRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (DeletePerson_Request) сообщения DeletePersonRequest не соответствует значению по умолчанию (DeletePerson).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_Client.SoapAPI.DeletePersonResponse DeletePerson(SOA_Client.SoapAPI.DeletePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.DeletePersonResponse> DeletePersonAsync(SOA_Client.SoapAPI.DeletePersonRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ListLanguages_Request) сообщения ListLanguagesRequest не соответствует значению по умолчанию (ListLanguages).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_Client.SoapAPI.ListLanguagesResponse ListLanguages(SOA_Client.SoapAPI.ListLanguagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.ListLanguagesResponse> ListLanguagesAsync(SOA_Client.SoapAPI.ListLanguagesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (CreateLanguage_Request) сообщения CreateLanguageRequest не соответствует значению по умолчанию (CreateLanguage).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_Client.SoapAPI.CreateLanguageResponse CreateLanguage(SOA_Client.SoapAPI.CreateLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.CreateLanguageResponse> CreateLanguageAsync(SOA_Client.SoapAPI.CreateLanguageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ReadLanguage_Request) сообщения ReadLanguageRequest не соответствует значению по умолчанию (ReadLanguage).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_Client.SoapAPI.ReadLanguageResponse ReadLanguage(SOA_Client.SoapAPI.ReadLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.ReadLanguageResponse> ReadLanguageAsync(SOA_Client.SoapAPI.ReadLanguageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (UpdateLanguage_Request) сообщения UpdateLanguageRequest не соответствует значению по умолчанию (UpdateLanguage).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_Client.SoapAPI.UpdateLanguageResponse UpdateLanguage(SOA_Client.SoapAPI.UpdateLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.UpdateLanguageResponse> UpdateLanguageAsync(SOA_Client.SoapAPI.UpdateLanguageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (DeleteLanguage_Request) сообщения DeleteLanguageRequest не соответствует значению по умолчанию (DeleteLanguage).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOA_Client.SoapAPI.DeleteLanguageResponse DeleteLanguage(SOA_Client.SoapAPI.DeleteLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.DeleteLanguageResponse> DeleteLanguageAsync(SOA_Client.SoapAPI.DeleteLanguageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePerson_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class CreatePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=1)]
        public int Age;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=2)]
        public string Mail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=3)]
        public int LanguageID;
        
        public CreatePersonRequest() {
        }
        
        public CreatePersonRequest(string Name, int Age, string Mail, int LanguageID) {
            this.Name = Name;
            this.Age = Age;
            this.Mail = Mail;
            this.LanguageID = LanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePerson_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class CreatePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public CreatePersonResponse() {
        }
        
        public CreatePersonResponse(bool state) {
            this.state = state;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
    public partial class SOAP_Person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int ageField;
        
        private string mailField;
        
        private int languageIDField;
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
                this.RaisePropertyChanged("Age");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("Mail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int LanguageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
                this.RaisePropertyChanged("LanguageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
    public partial class SOAP_Language : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPeople_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ListPeopleRequest {
        
        public ListPeopleRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListPeople_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ListPeopleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Person")]
        public SOA_Client.SoapAPI.SOAP_Person[] Person;
        
        public ListPeopleResponse() {
        }
        
        public ListPeopleResponse(SOA_Client.SoapAPI.SOAP_Person[] Person) {
            this.Person = Person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadPerson_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ReadPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        public ReadPersonRequest() {
        }
        
        public ReadPersonRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadPerson_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ReadPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public SOA_Client.SoapAPI.SOAP_Person Person;
        
        public ReadPersonResponse() {
        }
        
        public ReadPersonResponse(SOA_Client.SoapAPI.SOAP_Person Person) {
            this.Person = Person;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePerson_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class UpdatePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=1)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=2)]
        public int Age;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=3)]
        public string Mail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=4)]
        public int LanguageID;
        
        public UpdatePersonRequest() {
        }
        
        public UpdatePersonRequest(int ID, string Name, int Age, string Mail, int LanguageID) {
            this.ID = ID;
            this.Name = Name;
            this.Age = Age;
            this.Mail = Mail;
            this.LanguageID = LanguageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePerson_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class UpdatePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public UpdatePersonResponse() {
        }
        
        public UpdatePersonResponse(bool state) {
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePerson_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class DeletePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        public DeletePersonRequest() {
        }
        
        public DeletePersonRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePerson_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class DeletePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public DeletePersonResponse() {
        }
        
        public DeletePersonResponse(bool state) {
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListLanguages_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ListLanguagesRequest {
        
        public ListLanguagesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListLanguages_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ListLanguagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Language")]
        public SOA_Client.SoapAPI.SOAP_Language[] Language;
        
        public ListLanguagesResponse() {
        }
        
        public ListLanguagesResponse(SOA_Client.SoapAPI.SOAP_Language[] Language) {
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateLanguage_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class CreateLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string Name;
        
        public CreateLanguageRequest() {
        }
        
        public CreateLanguageRequest(string Name) {
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateLanguage_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class CreateLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public CreateLanguageResponse() {
        }
        
        public CreateLanguageResponse(bool state) {
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadLanguage_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ReadLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        public ReadLanguageRequest() {
        }
        
        public ReadLanguageRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadLanguage_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class ReadLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public SOA_Client.SoapAPI.SOAP_Language Language;
        
        public ReadLanguageResponse() {
        }
        
        public ReadLanguageResponse(SOA_Client.SoapAPI.SOAP_Language Language) {
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateLanguage_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class UpdateLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=1)]
        public string Name;
        
        public UpdateLanguageRequest() {
        }
        
        public UpdateLanguageRequest(int ID, string Name) {
            this.ID = ID;
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateLanguage_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class UpdateLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public UpdateLanguageResponse() {
        }
        
        public UpdateLanguageResponse(bool state) {
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteLanguage_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class DeleteLanguageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int ID;
        
        public DeleteLanguageRequest() {
        }
        
        public DeleteLanguageRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteLanguage_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class DeleteLanguageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public bool state;
        
        public DeleteLanguageResponse() {
        }
        
        public DeleteLanguageResponse(bool state) {
            this.state = state;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServicePortTypeChannel : SOA_Client.SoapAPI.MyServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServicePortTypeClient : System.ServiceModel.ClientBase<SOA_Client.SoapAPI.MyServicePortType>, SOA_Client.SoapAPI.MyServicePortType {
        
        public MyServicePortTypeClient() {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_Client.SoapAPI.CreatePersonResponse SOA_Client.SoapAPI.MyServicePortType.CreatePerson(SOA_Client.SoapAPI.CreatePersonRequest request) {
            return base.Channel.CreatePerson(request);
        }
        
        public bool CreatePerson(string Name, int Age, string Mail, int LanguageID) {
            SOA_Client.SoapAPI.CreatePersonRequest inValue = new SOA_Client.SoapAPI.CreatePersonRequest();
            inValue.Name = Name;
            inValue.Age = Age;
            inValue.Mail = Mail;
            inValue.LanguageID = LanguageID;
            SOA_Client.SoapAPI.CreatePersonResponse retVal = ((SOA_Client.SoapAPI.MyServicePortType)(this)).CreatePerson(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.CreatePersonResponse> SOA_Client.SoapAPI.MyServicePortType.CreatePersonAsync(SOA_Client.SoapAPI.CreatePersonRequest request) {
            return base.Channel.CreatePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_Client.SoapAPI.CreatePersonResponse> CreatePersonAsync(string Name, int Age, string Mail, int LanguageID) {
            SOA_Client.SoapAPI.CreatePersonRequest inValue = new SOA_Client.SoapAPI.CreatePersonRequest();
            inValue.Name = Name;
            inValue.Age = Age;
            inValue.Mail = Mail;
            inValue.LanguageID = LanguageID;
            return ((SOA_Client.SoapAPI.MyServicePortType)(this)).CreatePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_Client.SoapAPI.ListPeopleResponse SOA_Client.SoapAPI.MyServicePortType.ListPeople(SOA_Client.SoapAPI.ListPeopleRequest request) {
            return base.Channel.ListPeople(request);
        }
        
        public SOA_Client.SoapAPI.SOAP_Person[] ListPeople() {
            SOA_Client.SoapAPI.ListPeopleRequest inValue = new SOA_Client.SoapAPI.ListPeopleRequest();
            SOA_Client.SoapAPI.ListPeopleResponse retVal = ((SOA_Client.SoapAPI.MyServicePortType)(this)).ListPeople(inValue);
            return retVal.Person;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.ListPeopleResponse> SOA_Client.SoapAPI.MyServicePortType.ListPeopleAsync(SOA_Client.SoapAPI.ListPeopleRequest request) {
            return base.Channel.ListPeopleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_Client.SoapAPI.ListPeopleResponse> ListPeopleAsync() {
            SOA_Client.SoapAPI.ListPeopleRequest inValue = new SOA_Client.SoapAPI.ListPeopleRequest();
            return ((SOA_Client.SoapAPI.MyServicePortType)(this)).ListPeopleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_Client.SoapAPI.ReadPersonResponse SOA_Client.SoapAPI.MyServicePortType.ReadPerson(SOA_Client.SoapAPI.ReadPersonRequest request) {
            return base.Channel.ReadPerson(request);
        }
        
        public SOA_Client.SoapAPI.SOAP_Person ReadPerson(int ID) {
            SOA_Client.SoapAPI.ReadPersonRequest inValue = new SOA_Client.SoapAPI.ReadPersonRequest();
            inValue.ID = ID;
            SOA_Client.SoapAPI.ReadPersonResponse retVal = ((SOA_Client.SoapAPI.MyServicePortType)(this)).ReadPerson(inValue);
            return retVal.Person;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.ReadPersonResponse> SOA_Client.SoapAPI.MyServicePortType.ReadPersonAsync(SOA_Client.SoapAPI.ReadPersonRequest request) {
            return base.Channel.ReadPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_Client.SoapAPI.ReadPersonResponse> ReadPersonAsync(int ID) {
            SOA_Client.SoapAPI.ReadPersonRequest inValue = new SOA_Client.SoapAPI.ReadPersonRequest();
            inValue.ID = ID;
            return ((SOA_Client.SoapAPI.MyServicePortType)(this)).ReadPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_Client.SoapAPI.UpdatePersonResponse SOA_Client.SoapAPI.MyServicePortType.UpdatePerson(SOA_Client.SoapAPI.UpdatePersonRequest request) {
            return base.Channel.UpdatePerson(request);
        }
        
        public bool UpdatePerson(int ID, string Name, int Age, string Mail, int LanguageID) {
            SOA_Client.SoapAPI.UpdatePersonRequest inValue = new SOA_Client.SoapAPI.UpdatePersonRequest();
            inValue.ID = ID;
            inValue.Name = Name;
            inValue.Age = Age;
            inValue.Mail = Mail;
            inValue.LanguageID = LanguageID;
            SOA_Client.SoapAPI.UpdatePersonResponse retVal = ((SOA_Client.SoapAPI.MyServicePortType)(this)).UpdatePerson(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.UpdatePersonResponse> SOA_Client.SoapAPI.MyServicePortType.UpdatePersonAsync(SOA_Client.SoapAPI.UpdatePersonRequest request) {
            return base.Channel.UpdatePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_Client.SoapAPI.UpdatePersonResponse> UpdatePersonAsync(int ID, string Name, int Age, string Mail, int LanguageID) {
            SOA_Client.SoapAPI.UpdatePersonRequest inValue = new SOA_Client.SoapAPI.UpdatePersonRequest();
            inValue.ID = ID;
            inValue.Name = Name;
            inValue.Age = Age;
            inValue.Mail = Mail;
            inValue.LanguageID = LanguageID;
            return ((SOA_Client.SoapAPI.MyServicePortType)(this)).UpdatePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_Client.SoapAPI.DeletePersonResponse SOA_Client.SoapAPI.MyServicePortType.DeletePerson(SOA_Client.SoapAPI.DeletePersonRequest request) {
            return base.Channel.DeletePerson(request);
        }
        
        public bool DeletePerson(int ID) {
            SOA_Client.SoapAPI.DeletePersonRequest inValue = new SOA_Client.SoapAPI.DeletePersonRequest();
            inValue.ID = ID;
            SOA_Client.SoapAPI.DeletePersonResponse retVal = ((SOA_Client.SoapAPI.MyServicePortType)(this)).DeletePerson(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.DeletePersonResponse> SOA_Client.SoapAPI.MyServicePortType.DeletePersonAsync(SOA_Client.SoapAPI.DeletePersonRequest request) {
            return base.Channel.DeletePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_Client.SoapAPI.DeletePersonResponse> DeletePersonAsync(int ID) {
            SOA_Client.SoapAPI.DeletePersonRequest inValue = new SOA_Client.SoapAPI.DeletePersonRequest();
            inValue.ID = ID;
            return ((SOA_Client.SoapAPI.MyServicePortType)(this)).DeletePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_Client.SoapAPI.ListLanguagesResponse SOA_Client.SoapAPI.MyServicePortType.ListLanguages(SOA_Client.SoapAPI.ListLanguagesRequest request) {
            return base.Channel.ListLanguages(request);
        }
        
        public SOA_Client.SoapAPI.SOAP_Language[] ListLanguages() {
            SOA_Client.SoapAPI.ListLanguagesRequest inValue = new SOA_Client.SoapAPI.ListLanguagesRequest();
            SOA_Client.SoapAPI.ListLanguagesResponse retVal = ((SOA_Client.SoapAPI.MyServicePortType)(this)).ListLanguages(inValue);
            return retVal.Language;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.ListLanguagesResponse> SOA_Client.SoapAPI.MyServicePortType.ListLanguagesAsync(SOA_Client.SoapAPI.ListLanguagesRequest request) {
            return base.Channel.ListLanguagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_Client.SoapAPI.ListLanguagesResponse> ListLanguagesAsync() {
            SOA_Client.SoapAPI.ListLanguagesRequest inValue = new SOA_Client.SoapAPI.ListLanguagesRequest();
            return ((SOA_Client.SoapAPI.MyServicePortType)(this)).ListLanguagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_Client.SoapAPI.CreateLanguageResponse SOA_Client.SoapAPI.MyServicePortType.CreateLanguage(SOA_Client.SoapAPI.CreateLanguageRequest request) {
            return base.Channel.CreateLanguage(request);
        }
        
        public bool CreateLanguage(string Name) {
            SOA_Client.SoapAPI.CreateLanguageRequest inValue = new SOA_Client.SoapAPI.CreateLanguageRequest();
            inValue.Name = Name;
            SOA_Client.SoapAPI.CreateLanguageResponse retVal = ((SOA_Client.SoapAPI.MyServicePortType)(this)).CreateLanguage(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.CreateLanguageResponse> SOA_Client.SoapAPI.MyServicePortType.CreateLanguageAsync(SOA_Client.SoapAPI.CreateLanguageRequest request) {
            return base.Channel.CreateLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_Client.SoapAPI.CreateLanguageResponse> CreateLanguageAsync(string Name) {
            SOA_Client.SoapAPI.CreateLanguageRequest inValue = new SOA_Client.SoapAPI.CreateLanguageRequest();
            inValue.Name = Name;
            return ((SOA_Client.SoapAPI.MyServicePortType)(this)).CreateLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_Client.SoapAPI.ReadLanguageResponse SOA_Client.SoapAPI.MyServicePortType.ReadLanguage(SOA_Client.SoapAPI.ReadLanguageRequest request) {
            return base.Channel.ReadLanguage(request);
        }
        
        public SOA_Client.SoapAPI.SOAP_Language ReadLanguage(int ID) {
            SOA_Client.SoapAPI.ReadLanguageRequest inValue = new SOA_Client.SoapAPI.ReadLanguageRequest();
            inValue.ID = ID;
            SOA_Client.SoapAPI.ReadLanguageResponse retVal = ((SOA_Client.SoapAPI.MyServicePortType)(this)).ReadLanguage(inValue);
            return retVal.Language;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.ReadLanguageResponse> SOA_Client.SoapAPI.MyServicePortType.ReadLanguageAsync(SOA_Client.SoapAPI.ReadLanguageRequest request) {
            return base.Channel.ReadLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_Client.SoapAPI.ReadLanguageResponse> ReadLanguageAsync(int ID) {
            SOA_Client.SoapAPI.ReadLanguageRequest inValue = new SOA_Client.SoapAPI.ReadLanguageRequest();
            inValue.ID = ID;
            return ((SOA_Client.SoapAPI.MyServicePortType)(this)).ReadLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_Client.SoapAPI.UpdateLanguageResponse SOA_Client.SoapAPI.MyServicePortType.UpdateLanguage(SOA_Client.SoapAPI.UpdateLanguageRequest request) {
            return base.Channel.UpdateLanguage(request);
        }
        
        public bool UpdateLanguage(int ID, string Name) {
            SOA_Client.SoapAPI.UpdateLanguageRequest inValue = new SOA_Client.SoapAPI.UpdateLanguageRequest();
            inValue.ID = ID;
            inValue.Name = Name;
            SOA_Client.SoapAPI.UpdateLanguageResponse retVal = ((SOA_Client.SoapAPI.MyServicePortType)(this)).UpdateLanguage(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.UpdateLanguageResponse> SOA_Client.SoapAPI.MyServicePortType.UpdateLanguageAsync(SOA_Client.SoapAPI.UpdateLanguageRequest request) {
            return base.Channel.UpdateLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_Client.SoapAPI.UpdateLanguageResponse> UpdateLanguageAsync(int ID, string Name) {
            SOA_Client.SoapAPI.UpdateLanguageRequest inValue = new SOA_Client.SoapAPI.UpdateLanguageRequest();
            inValue.ID = ID;
            inValue.Name = Name;
            return ((SOA_Client.SoapAPI.MyServicePortType)(this)).UpdateLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOA_Client.SoapAPI.DeleteLanguageResponse SOA_Client.SoapAPI.MyServicePortType.DeleteLanguage(SOA_Client.SoapAPI.DeleteLanguageRequest request) {
            return base.Channel.DeleteLanguage(request);
        }
        
        public bool DeleteLanguage(int ID) {
            SOA_Client.SoapAPI.DeleteLanguageRequest inValue = new SOA_Client.SoapAPI.DeleteLanguageRequest();
            inValue.ID = ID;
            SOA_Client.SoapAPI.DeleteLanguageResponse retVal = ((SOA_Client.SoapAPI.MyServicePortType)(this)).DeleteLanguage(inValue);
            return retVal.state;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOA_Client.SoapAPI.DeleteLanguageResponse> SOA_Client.SoapAPI.MyServicePortType.DeleteLanguageAsync(SOA_Client.SoapAPI.DeleteLanguageRequest request) {
            return base.Channel.DeleteLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOA_Client.SoapAPI.DeleteLanguageResponse> DeleteLanguageAsync(int ID) {
            SOA_Client.SoapAPI.DeleteLanguageRequest inValue = new SOA_Client.SoapAPI.DeleteLanguageRequest();
            inValue.ID = ID;
            return ((SOA_Client.SoapAPI.MyServicePortType)(this)).DeleteLanguageAsync(inValue);
        }
    }
}
